// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyENEM.API.Data;

#nullable disable

namespace StudyENEM.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911194758_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyENEM.API.Models.Alternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("Letter")
                        .HasColumnType("character(1)")
                        .HasColumnName("letra");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("questao_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Letter")
                        .IsUnique();

                    b.ToTable("alternativa", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("sigla");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("area", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Attempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<string>("ForeignLanguage")
                        .HasColumnType("text")
                        .HasColumnName("lingua_estrangeira");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_limite_segundos");

                    b.Property<int?>("TimeTakenSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_total_segundos");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("conteudo_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("simulado", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.AttemptAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("simulado_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("correta");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("questao_id");

                    b.Property<char?>("SelectedOption")
                        .HasColumnType("character(1)")
                        .HasColumnName("alternativa_selecionada");

                    b.Property<int?>("TimeSpentSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resposta_segundos");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("resposta", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.AttemptResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("simulado_id");

                    b.Property<double?>("AverageTimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("tempo_medio_segundos");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentual_acerto");

                    b.Property<int>("TotalCorrect")
                        .HasColumnType("integer")
                        .HasColumnName("total_acertos");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questoes");

                    b.Property<int>("TriItems")
                        .HasColumnType("integer")
                        .HasColumnName("itens_tri");

                    b.Property<double?>("TriScore")
                        .HasColumnType("double precision")
                        .HasColumnName("nota_tri");

                    b.Property<double?>("TriStandardError")
                        .HasColumnType("double precision")
                        .HasColumnName("erro_padrao_tri");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AttemptId");

                    b.ToTable("resultado", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<string>("ClassificationMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metodo_classificacao");

                    b.Property<char?>("CorrectOption")
                        .HasColumnType("character(1)")
                        .HasColumnName("gabarito");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("dia");

                    b.Property<string>("ForeignLanguage")
                        .HasColumnType("text")
                        .HasColumnName("lingua_estrangeira");

                    b.Property<int>("InepItemCode")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_item_inep");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidade_id");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enunciado");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("conteudo_id");

                    b.Property<double?>("TriA")
                        .HasColumnType("double precision")
                        .HasColumnName("tri_a");

                    b.Property<double?>("TriB")
                        .HasColumnType("double precision")
                        .HasColumnName("tri_b");

                    b.Property<double?>("TriC")
                        .HasColumnType("double precision")
                        .HasColumnName("tri_c");

                    b.Property<string>("TriExclusionReason")
                        .HasColumnType("text")
                        .HasColumnName("motivo_exclusao_tri");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("SkillId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TopicId");

                    b.HasIndex("Year", "Number", "ForeignLanguage")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Year", "Number", "ForeignLanguage"), false);

                    b.ToTable("questao", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<int>("Competency")
                        .HasColumnType("integer")
                        .HasColumnName("competencia");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Code")
                        .IsUnique();

                    b.ToTable("habilidade", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Name")
                        .IsUnique();

                    b.ToTable("disciplina", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("conteudo", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.TriScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<double>("CalibrationMaxError")
                        .HasColumnType("double precision")
                        .HasColumnName("calibracao_erro_maximo");

                    b.Property<double>("CalibrationRmse")
                        .HasColumnType("double precision")
                        .HasColumnName("calibracao_rmse");

                    b.Property<int>("CalibrationSampleSize")
                        .HasColumnType("integer")
                        .HasColumnName("calibracao_participantes");

                    b.Property<double>("Intercept")
                        .HasColumnType("double precision")
                        .HasColumnName("intercepto");

                    b.Property<double>("Slope")
                        .HasColumnType("double precision")
                        .HasColumnName("inclinacao");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Year")
                        .IsUnique();

                    b.ToTable("escala_tri", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_salt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("StudyENEM.API.Models.Alternative", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Question", "Question")
                        .WithMany("Alternatives")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Attempt", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyENEM.API.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyENEM.API.Models.User", "User")
                        .WithMany("Attempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyENEM.API.Models.AttemptAnswer", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyENEM.API.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StudyENEM.API.Models.AttemptResult", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyENEM.API.Models.Attempt", "Attempt")
                        .WithMany("Results")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Question", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyENEM.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyENEM.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyENEM.API.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Skill");

                    b.Navigation("Subject");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Skill", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Subject", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Area", "Area")
                        .WithMany("Subjects")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Topic", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyENEM.API.Models.TriScale", b =>
                {
                    b.HasOne("StudyENEM.API.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Area", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Attempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Question", b =>
                {
                    b.Navigation("Alternatives");

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("StudyENEM.API.Models.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("StudyENEM.API.Models.User", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
